const express = require('express')
const inscriptionController = require('../Controllers/inscriptionController')
const {validateToken} = require('../middleware/auth')
const router = express.Router()

router.post('/create' , validateToken, inscriptionController.createInscription)
router.post('/create2' , validateToken, inscriptionController.createInscription2)
router.post('/create3' , validateToken, inscriptionController.createInscription3)
router.post('/delete' , validateToken, inscriptionController.deleteInscription)
router.get('/get-by-poste-creneau' , validateToken, inscriptionController.getIncriptionsByPostCreneau)
router.get('/get-by-user/:iduser/:idcreneau' , validateToken, inscriptionController.getInscriptionsByUserCreneau)
router.get('/user/:iduser/:idfestival' , validateToken,inscriptionController.getInscriptionsOfUserByFestival)
router.post('/registered' , validateToken,inscriptionController.getRegisteredPeopleByCreneau)
router.post('/validation' , validateToken,inscriptionController.validateRegistration)
router.get('/get-by-festival/:idfestival', validateToken ,inscriptionController.getInscriptionsByFestival)
module.exports = router;
